### ISSUE TITLE
Mask matrix transposed

### ISSUE THREAD

**Issue by LingyueSun** [brianmanderson/Dicom_RT_and_Images_to_Mask#13] opened 2021-03-11 19:55 UTC
the mask displayed on the MRI slices flipped diagonally, seems like there is a transpose of the mask matrix.

**Comment by brianmanderson** [comment] 2021-03-11 20:03
Thank you for finding this issue, this was caused by a swapping of the vertex_row and vertex_col coordinates and has been fixed in e023e6b

**Closed as completed by brianmanderson** 2021-03-11 20:03 UTC
