### ISSUE TITLE
Issue: Index is not present in the dictionary 

### ISSUE THREAD

**Issue by fedmastroleo** [brianmanderson/Dicom_RT_and_Images_to_Mask#24] opened 2022-12-28 10:27 UTC
Hello! 

Nice script. I'm trying to use it to make some conversions from DICOM to Nifti, but I'm not able to convert some DICOMs due to the error you find here attached. However, I'm able to open these files even with other viewers (such as slicer). 

Do you have any advice how to solve this issue? 

Thanks

```
Compiling dictionaries together...
0 unique series IDs were found. Default is index 0, to change use set_index(index)
```

```
AssertionError                            Traceback (most recent call last)
Input In [35], in <cell line: 1>()
      1 for file in alldicomfolder:
      2     print(f"Processing {file}")
----> 3     d2nconvfold(file, output_dir)

Input In [32], in d2nconvfold(xinput, xoutput)
      2 reader = DicomReaderWriter()
      3 reader.walk_through_folders(xinput)
----> 4 reader.get_images()
      6 initial_file = os.path.basename(xinput)
      8 sitk.WriteImage(reader.dicom_handle, xoutput + "/" + initial_file + '_0000.nii.gz')

File ~/opt/anaconda3/envs/amd_gpu/lib/python3.8/site-packages/DicomRTTool/ReaderWriter.py:804, in DicomReaderWriter.get_images(self)
    803 def get_images(self) -> None:
--> 804     assert self.index in self.series_instances_dictionary, \
    805         'Index is not present in the dictionary! Set it using set_index(index)'
    806     index = self.index
    807     series_instance_uid = self.series_instances_dictionary[index]['SeriesInstanceUID']

AssertionError: Index is not present in the dictionary! Set it using set_index(index)
```

**Comment by brianmanderson** [comment] 2023-01-08 20:39
Hello! And happy new year!

I'm sorry you're having an issue with the code. It appears that the problem is that there isn't any images included with the DICOM being sent (I'm assuming you're trying to load some RT Structure files)

You can fix this by including the image (CT, MR, etc.) that is associated with the RT Structure within the folder

In the future, I'll write an update that allows for structures to be viewed without the associated image, but since this was originally written deep learning segmentation, it was expected to include an image

Please tell me if this helps!
Brian

**Comment by brianmanderson** [comment] 2023-01-23 21:01
Closing this for now, please reopen if this odes not help

Brian

**Closed as completed by brianmanderson** 2023-01-23 21:01 UTC
